[workspace]
authors = ["Uğur <beratugursolmaz@yahoo.com>"]
channels = ["conda-forge"]
name = "spark"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pyspark = ">=4.0.0,<5"
findspark = ">=2.0.1,<3"
jupyter = ">=1.1.1,<2"
openjdk = "8.*"
transformers = ">=4.52.3,<5"
datasets = ">=3.5.0,<4"
evaluate = ">=0.4.3,<0.5"
scikit-learn = ">=1.6.1,<2"
pytorch = ">=2.6.0,<3"
protobuf = ">=5.29.3,<6"
wrapt = ">=1.17.2,<2"
pip = ">=25.1,<26"
streamlit = ">=1.45.1,<2"
matplotlib = ">=3.10.3,<4"
pandas = ">=2.2.3,<3"
joblib = ">=1.5.1,<2"
notebook = ">=7.4.3,<8"
